#!/bin/bash

function aptupdate() {
    # When called it runs apt update, but at most once every hour
    # otherwise it is skipped.
    SENTINEL=/var/tmp/aptupdate
    if [ -e $SENTINEL ] && [ 3600 -gt $(expr $(date +%s) - $(stat -c %Y $SENTINEL)) ]; then
        return
    fi

    apt update
    touch $SENTINEL
}

BASE_DIR="$(
    cd "$(dirname "$0")"
    pwd
)"
source "${BASE_DIR}/data/settings.config"

os_ver=$(grep "^PRETTY_NAME=\"${expected_os}\"" /etc/os-release)
if [ -z "$os_ver" ]; then
    echo "${error_message}"
    exit 1
fi

# Wait until appliance is not busy so that sshd_config is properly applied after reboot
status=$(cz-config status | jq -r .roles.appliance.status)
while [[ $status == "busy" ]]; do
    sleep 5
    status=$(cz-config status | jq -r .roles.appliance.status)
done

# V-270675
# V-270815
pushd /usr/sbin
if ! test -e .patched_cz_install; then
    patch -p1 <"$BASE_DIR/data/cz-install.patch"
    touch .patched_cz_install
fi
popd
cz-install bootmenu $(cat /mnt/state/volume-number)

mkdir -p /etc/audit/rules.d/
echo "" >/etc/audit/rules.d/audit.rules
cp "$BASE_DIR/data/10-base-config.rules" /etc/audit/rules.d/
cp "$BASE_DIR/data/30-stig.rules" /etc/audit/rules.d/
cp "$BASE_DIR/data/99-finalize.rules" /etc/audit/rules.d/
augenrules --load

# V-270775
chmod -R 0640 /etc/audit/audit*.{rules,conf} /etc/audit/rules.d/*

if dpkg -l | grep \ auditd\  >/dev/null; then
    # If auditd is installed it is disabled by default
    touch /etc/cz_stig
else
    aptupdate
    # V-270657
    # Install auditd
    apt install -o DPkg::Options::="--force-confold" -y auditd
fi

# V-270829
sed -i "s/log_group = adm/log_group = root/g" /etc/audit/auditd.conf

service auditd restart

# V-270707
# Require password for sudo, only if cz has a password set
if grep '^cz:\$' </etc/shadow >/dev/null; then
    sed -i "s/NOPASSWD://g" /etc/sudoers
fi

# V-270736
# FIXME we don't use smart card authentication
mkdir -p /etc/pam_pkcs11/
echo "use_mappers = pwent" > /etc/pam_pkcs11/pam_pkcs11.conf
echo "  # Certificate Common Name ( CN ) to getpwent() mapper
  mapper pwent {
       debug = false;
       ignorecase = false;
       module = internal;
       # module = /lib/x86_64-linux-gnu/pam_pkcs11/pwent_mapper.so;
  }" >> /etc/pam_pkcs11/pam_pkcs11.conf


# V-270710
sed -i '1i session required pam_lastlog.so showfailed' /etc/pam.d/login

# V-270757
chmod 750 /run/log/journal
chmod 750 /var/log/journal

# V-270756
chmod o-r /var/log/* /var/log/apt/*

# V-270680
# Verify the operating system automatically terminates a user session after inactivity timeouts have expired.
# This decreases timeout from 20 minutes to 10 minutes
sed -i "s:TMOUT=1800:TMOUT=600:g" /etc/profile.d/autologout.sh

# V-270716
# Verify the Ubuntu operating system defines default permissions for all authenticated
# users in such a way that the user can read and modify only their own files.
sed -i "s:UMASK.*:UMASK 077:g" /etc/login.defs

# V-270730
grep -v ^PASS_MIN_DAYS < /etc/login.defs > /etc/login.defs.tmp
cat /etc/login.defs.tmp > /etc/login.defs
echo "PASS_MIN_DAYS 1" >> /etc/login.defs

# V-270742
# Verify that all network connections associated with SSH traffic automatically terminate
# after a period of inactivity.
sed -i "s:ClientAliveCountMax 0:ClientAliveCountMax 1:g" /etc/ssh/sshd_config

# V-270668
# Verify the SSH daemon is configured to only use MACs that employ FIPS 140-2 approved ciphers
sed -i "s:MACs .*:MACs hmac-sha2-512,hmac-sha2-256:g" /etc/ssh/sshd_config

# V-270667
# Verify the SSH daemon is configured to only implement FIPS-approved algorithms
sed -i "s:Ciphers .*:Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr:g" /etc/ssh/sshd_config

# V-270709
# Verify the SSH daemon prevents remote hosts from connecting to the proxy display.
echo "X11UseLocalhost yes" >>/etc/ssh/sshd_config

# Reload sshd daemon to enforce above changes
systemctl reload sshd.service

# V-270693
# Verify the Ubuntu operating system displays the Standard Mandatory DoD Notice and
# Consent Banner before granting access to the operating system via an SSH logon
echo "$dod_consent_banner" >/etc/issue.net

# V-270726
echo "ucredit=-1" >>/etc/security/pwquality.conf

# V-270727
echo "lcredit=-1" >>/etc/security/pwquality.conf

# V-270728
echo "dcredit=-1" >>/etc/security/pwquality.conf

# V-270729
echo "difok=8" >>/etc/security/pwquality.conf

# V-270732
# Verify the pwquality configuration file enforces a minimum 15-character password length
echo minlen=15 >>/etc/security/pwquality.conf

# V-270733
echo "ocredit=-1" >>/etc/security/pwquality.conf

# V-270704
# Verify the Ubuntu operating system uses the "cracklib" library to prevent the use of dictionary words
echo dictcheck=1 >>/etc/security/pwquality.conf

# V-270705
echo enforcing=1 >>/etc/security/pwquality.conf
echo "password requisite pam_pwquality.so retry=3" >>/etc/pam.d/common-password

# V-270725
cp -a /etc/pam.d/common-password /etc/pam.d/common-password.new
grep -v pam_unix.so </etc/pam.d/common-password.new >/etc/pam.d/common-password
echo "password [success=1 default=ignore] pam_unix.so obscure sha512 shadow remember=5 rounds=100000" >>/etc/pam.d/common-password
rm /etc/pam.d/common-password.new

# V-270705
# Install libpam-pwquality
if ! dpkg -l | grep libpam-pwquality >/dev/null; then
    aptupdate
    apt install -o DPkg::Options::="--force-confold" -y libpam-pwquality
fi

# V-270674
# Install vlock
if ! dpkg -l | grep vlock >/dev/null; then
    aptupdate
    apt install -o DPkg::Options::="--force-confold" -y vlock
    # V-270697 except this file+symlink
    rm -f /usr/lib/vlock/modules/nosysrq.so
    rm -f /lib/vlock/modules/nosysrq.so
fi

# V-270773
# Verify is configured to remove all software components after updated versions have been installed
cat >/etc/apt/apt.conf.d/50unattended-upgrades <<-EOM
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
EOM

# V-270676
# Pass audit=1 to the kernel command line
if ! cz-config get kernel/cmdlineOptions | grep audit=1 >/dev/null; then
    cz-config set kernel/cmdlineOptions "$(cz-config get kernel/cmdlineOptions) audit=1"
fi

# V-270681
# Monitor remote access methods
cp "$BASE_DIR/data/55-auth.conf" /etc/rsyslog.d/
systemctl restart rsyslog.service

# V-270712
rm -f /etc/systemd/system/ctrl-alt-del.target
systemctl disable ctrl-alt-del.target
systemctl mask ctrl-alt-del.target
systemctl daemon-reload

# V-270767
chmod 0755 /var/log


# V-270758
chmod 740 /usr/bin/journalctl

# V-270697
find -L /lib /usr/lib /lib64 /usr/lib64 -type f ! -group root -exec chgrp root -- {} +

# V-270742
# V-270741
cp -a /etc/ssh/sshd_config /etc/ssh/sshd_config.new
grep -vE "ClientAliveCountMax|UsePAM" < /etc/ssh/sshd_config.new > /etc/ssh/sshd_config
echo 'ClientAliveCountMax 1' >> /etc/ssh/sshd_config
echo 'UsePAM yes' >> /etc/ssh/sshd_config
systemctl restart sshd.service

# V-270718
echo install usb-storage /bin/false >> /etc/modprobe.d/stig.conf
echo blacklist usb-storage >> /etc/modprobe.d/stig.conf

# V-270724
passwd -l root

# V-270731
cp -a /etc/login.defs /etc/login.defs.new
grep -v "PASS_MAX_DAYS" < /etc/login.defs.new > /etc/login.defs
echo 'PASS_MAX_DAYS 60' >> /etc/login.defs

# V-270683
useradd -D -f 35

# V-270659
apt install -y apparmor

# V-270649
apt install -y aide

# V-270652
if ! grep -q "SILENTREPORTS=no" /etc/default/aide
then
  echo "SILENTREPORTS=no" >> /etc/default/aide
fi

# V-270831
aide_str="# Audit Tools
/sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/audispd p+i+n+u+g+s+b+acl+xattrs+sha512"

if ! grep -Fxq "# Audit tools" /etc/aide.conf
then
  echo "$aide_str" >> /etc/aide.conf
  augenrules --load
fi

# V-270746
systemctl mask kdump-tools

# V-270690
sed -i 's/auth\t\[success=1 default=ignore\]\tpam_unix.so/auth\t[success=1 default=ignore]\tpam_unix.so\nauth\t[default=die]\tpam_faillock.so\tauthfail\nauth\tsufficient\tpam_faillock.so\tauthsucc /' /etc/pam.d/common-auth
echo "audit
silent
deny = 3
fail_interval = 900
unlock_time = 0" >> /etc/security/faillock.conf

# V-270706
echo "auth required pam_faildelay.so delay=4000000" >> /etc/pam.d/common-auth

# V-270677
if ! grep -q "\* hard maxlogins 10" /etc/security/limits.conf
then
  echo "* hard maxlogins 10" >> /etc/security/limits.conf
fi

# V-270818
cp -a /etc/audit/auditd.conf /etc/audit/auditd.conf.new
grep -vE "^space_left |^space_left_action " < /etc/audit/auditd.conf.new > /etc/audit/auditd.conf
echo "space_left = 25%
space_left_action = email " >> /etc/audit/auditd.conf
systemctl restart auditd.service

# V-270713
sed -i 's/nullok//' /etc/pam.d/common-auth
sed -i 's/nullok//' /etc/pam.d/common-password

# V-270756
find /var/log -perm /137 ! -name '*[bw]tmp' ! -name '*lastlog' -type f -exec chmod 640 '{}' \;
rm /var/log/README

# V-270670
accepted_ciphers="    Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr"
sed -Ei "s/#\s{3,4}Ciphers.*$/${accepted_ciphers}/" /etc/ssh/ssh_config
systemctl restart ssh
