#!/bin/bash

#load shared vars
BASE_DIR="$(cd "$(dirname "$0")"; pwd)";
source "${BASE_DIR}/data/settings.config"

os_ver=$(grep "^PRETTY_NAME=\"${expected_os}\"" /etc/os-release)
if [ -z "$os_ver" ]; then
	echo "${error_message}"
	exit 1
fi