#!/bin/bash

#load shared vars
BASE_DIR="$(cd "$(dirname "$0")"; pwd)";
source "${BASE_DIR}/data/settings.config"

os_ver=$(grep "^PRETTY_NAME=\"${expected_os}\"" /etc/os-release)
if [ -z "$os_ver" ]; then
	echo "${error_message}"
	exit 1
fi

#V-219212 
systemctl unmask ctrl-alt-del.target
systemctl daemon-reload

#V-219156 V-260477
rm /etc/apt/apt.conf.d/50unattended-upgrades 

#V-219181 & V-219184
rm /etc/security/pwquality.conf

#V-219303
sed -i "s:900:1800:g" /etc/profile.d/autologout.sh

#V-219328
sed -i "s:K 077:K 027:g" /etc/login.defs

#V-219339
rm /etc/modprobe.d/DISASTIG.conf

# V-260589
rm /etc/rsyslog.d/55-auth.conf
systemctl restart rsyslog
